# part 1

import all necessary libraries (i.e. pandas and matplotlib)

In [2]:
# your code here
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

Read the provided file `titanic.csv` into a DataFrame

In [3]:
# your code here
titanic_df = pd.read_csv("titanic.csv")

print the following
- entries from the data frame
- descriptive statistics, what is the average age, the maximum number of siblings and children? 
- general information
- first 5 entries
- first 15 entries
- last 5 entries
- last 15 entries
- sample of random 10 entries

In [ ]:
# your code here

draw a histogram for age distribution using `matplotlib`

In [ ]:
# yoru code here

- Create a new DataFrame with only entries where age > 30.  
- Give number of such entires
- show only the women entries, how many  are there over the age of 30
- the men entries, how many men are there over the age of 30
- plot the new histogram for all ages >30, how does this histogram differ from the one you plotted above?

In [ ]:
# your code here

Use `pandas` to plot the pie chart of all classes on board the titanic.

In [ ]:
# your code here

use `pandas` to plot the bar chart of all towns that people embarked from.

In [ ]:
# your code here

# part 2

Create a new DataFrame with 3 columns: fare, class, embark_town.  Clean your data from all `NaN` values.  Sort your DataFrame by fare in decreasing order.  Sort the same data frame in alphabetical order of the embarked_town.

In [7]:
# your code here
fare_class_town_df = titanic_df[['fare', 'class', 'embark_town']]
fare_class_town_df = fare_class_town_df.dropna()
# fare_class_town_df.sort_values(by = ['fare', ascending = False])
fare_class_town_df.sort_values(by = ['embark_town'])

         fare   class  embark_town
258  512.3292   First    Cherbourg
125   11.2417   Third    Cherbourg
354    7.2250   Third    Cherbourg
352    7.2292   Third    Cherbourg
128   22.3583   Third    Cherbourg
..        ...     ...          ...
351   35.0000   First  Southampton
353   17.8000   Third  Southampton
355    9.5000   Third  Southampton
344   13.0000  Second  Southampton
445   81.8583   First  Southampton

[889 rows x 3 columns]

Create a new DataFrame that holds all entries with classes 2 or 3.  Plot the histogram.
In pandas `&` corresponds to logical `and`, and `|` corresponds to logical `or`

In [11]:
# your code here
class_23_filter = (titanic_df['pclass'] == 2) | (titanic_df['pclass'] == 3)
titanic_df[class_23_filter]

,survived,pclass,sex,age,sibsp,fare,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,7.2500,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,8.0500,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,8.4583,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,21.0750,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,7.0500,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,29.1250,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,13.0000,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,23.4500,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,7.7500,Third,man,True,NaN,Queenstown,no,True

Customize row indices such that indices are according to embarked town, drop all `NaN` values, and sort in alphabetical order of embarked town.

In [18]:
# your code here
titanic_by_town_df = titanic_df.set_index('embark_town')
titanic_by_town_df = titanic_by_town_df.dropna()
titanic_by_town_df.sort_values(by = ['embark_town'])

,survived,pclass,sex,age,sibsp,fare,class,who,adult_male,deck,alive,alone
embark_town,,,,,,,,,,,,
Cherbourg,1,1,female,38.0,1,71.2833,First,woman,False,C,yes,False
Cherbourg,0,1,male,18.0,1,108.9000,First,man,True,C,no,False
Cherbourg,1,1,female,54.0,1,78.2667,First,woman,False,D,yes,False
Cherbourg,0,1,male,58.0,0,29.7000,First,man,True,B,no,True
Cherbourg,1,1,male,25.0,1,91.0792,First,man,True,B,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Southampton,1,1,male,52.0,0,30.5000,First,man,True,C,yes,True
Southampton,0,1,male,47.0,0,52.0000,First,man,True,C,no,True
Southampton,0,1,male,65.0,0,26.5500,First,man,True,E,no,True
NaN,1,1,female,38.0,0,80.0000,First,woman,False,B,yes,True
NaN,1,1,female,62.0,0,80.0000,First,woman,False,B,yes,True

Let's aggregate data into groups and 
- get the number of entries from each class (i.e. pclass column in csv file)
- get number of entries from each town
- get general summary of each class
- get the number of entries from each class of only survivors
- plot women, men, children according to class

In [55]:
# your code here
#aggregation_df = titanic_df[['pclass', 'embark_town']]
#aggregation_df = (titanic_df['embark_town'] == 'Southampton')
#aggregation_df = aggregation_df.dropna()
#aggregation_df
titanic_df.groupby('pclass').size()
titanic_df.groupby('embark_town').size()
titanic_df.groupby('pclass').describe().round(2).T

titanic_df.groupby(['pclass', 'survived']).size()
titanic_df.groupby(['pclass', 'who']).count()

              survived  sex  age  sibsp  fare  class  adult_male  deck  \
pclass who
1      child         6    6    6      6     6      6           6     6
       man         119  119   98    119   119    119         119    91
       woman        91   91   82     91    91     91          91    78
2      child        19   19   19     19    19     19          19     4
       man          99   99   90     99    99     99          99     3
       woman        66   66   64     66    66     66          66     9
3      child        58   58   58     58    58     58          58     3
       man         319  319  225    319   319    319         319     5
       woman       114  114   72    114   114    114         114     4

              embark_town  alive  alone
pclass who
1      child            6      6      6
       man            119    119    119
       woman           89     91     91
2      child           19     19     19
       man             99     99     99
       woman           66     66     66
3      child           58     58     58
       man            319    319    319
       woman          114    114    114

plot a bar graph with the number of children, women and men for each class of ticket

In [ ]:
# your code here
titanic_df.groupby(['pclass', 'who']).size().unstack().plot(kind = 'bar', figsize = (5, 5)\
    title = 'Class Distribution of children, women, and men')

* plot a histogram that shows the number of people who survived and did not survive with age on the x-axis
* plot a histogram that shows the number of people in each class with age on the x-axis
* put the two plots beside each other horizontally

In [57]:
titanic_df.groupby(['survived', 'age']).size()

survived  age
0         1.0     2
          2.0     7
          3.0     1
          4.0     3
          6.0     1
                 ..
1         58.0    3
          60.0    2
          62.0    2
          63.0    2
          80.0    1
Length: 142, dtype: int64